CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  type TINYINT(1) NOT NULL DEFAULT 0,
  mail VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  firstName VARCHAR(100) NOT NULL,
  lastName VARCHAR(100) NOT NULL,
  birthDate DATE,
  city VARCHAR(255),
  phoneNumber VARCHAR(15)
);

CREATE TABLE IF NOT EXISTS coaches (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  mail VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  firstName VARCHAR(100) NOT NULL,
  lastName VARCHAR(100) NOT NULL,
  address VARCHAR(255),
  city VARCHAR(255),
  phoneNumber VARCHAR(15)
);

CREATE TABLE IF NOT EXISTS messages (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  fromId INT NOT NULL,
  fromType INT NOT NULL,
  toId INT NOT NULL,
  toType INT NOT NULL,
  date DATE,
  content TEXT
);